############ PULIZIA ALSHISTORY_Subject_symptoms rivista ############ 

setwd("~/Desktop/PROGETTO BAYESIANA/als_data/Modified_Data")

library(plyr)

als <- read.csv("ALSHistory_RP_Subjects_Symptoms.csv", header=T)
al <- als

al$LOCATION1[al$LOCATION1=="LEFT_FACE"]<-"FACE"
al$LOCATION1[al$LOCATION1=="TONGUE"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="ORAL__MUSCLES"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="DYSARTHRIA"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="ORAL"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="SLURRING"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="MUMBLING"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="NOSE"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="OROFACIAL"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="DYSATHRIA"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="MOUTH__JAW"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="SLOWING"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="DYSARTHROPHONIA"]<-"MOUTH"
al$LOCATION1[al$LOCATION1=="MOUTH__MASSETER"]<-"MOUTH"

al$LOCATION1[al$LOCATION1=="THROAT"]<-"PHARYNX"
al$LOCATION1[al$LOCATION1=="DYSPHAGIA"]<-"PHARYNX"
al$LOCATION1[al$LOCATION1=="ESOPHAGUS"]<-"PHARYNX"

al$LOCATION1[al$LOCATION1=="VOICE"]<-"LARYNX"
al$LOCATION1[al$LOCATION1=="DYSPHONIA"]<-"LARYNX"
al$LOCATION1[al$LOCATION1=="HOARSENESS"]<-"LARYNX"
al$LOCATION1[al$LOCATION1=="CHOCKING"]<-"LARYNX"
al$LOCATION1[al$LOCATION1=="VOCAL CORDS"]<-"LARYNX"
al$LOCATION1[al$LOCATION1=="VOICE__MODIFICATION"]<-"LARYNX"
al$LOCATION1[al$LOCATION1=="VARYING PITCH"]<-"LARYNX"

al$LOCATION1[al$LOCATION1=="HANDS__FINGERS"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__THUMB"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="LEFT_HAND"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__INTRINSIC MUSCLES"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="LEFT_HAND__FINGERS"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="LEFT_HAND__LITTLE FINGER"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="HANDS__THUMBS"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__LITTLE FINGER"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="LEFT_HAND__INDEX"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__RING"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__INDEX"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="HANDS__MUSCLES"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__FINGERS"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="LEFT_THENAR"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_WRIST"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__MUSCLES"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="RIGHT_HAND__MIDDLE"]<-"HANDS"
al$LOCATION1[al$LOCATION1=="LEFT_HAND__THUMB"]<-"HANDS"

al$LOCATION1[al$LOCATION1=="RIGHT_ARM"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="RIGHT_ARM__DISTAL"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="RIGHT_ARM__PROXIMAL"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="LEFT_ARM"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="LEFT_ARM__DISTAL"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="LEFT_ARM__PROXIMAL"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="ARMS__PROXIMAL"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="ARMS__DISTAL"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="ARMS__UPPER"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="RIGHT_FOREARM"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="RIGHT_ELBOW"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="RIGHT_BICEPS"]<-"ARMS"
al$LOCATION1[al$LOCATION1=="LEFT_BICEPS"]<-"ARMS"

al$LOCATION1[al$LOCATION1=="RIGHT_ANKLE"]<-"FEET"
al$LOCATION1[al$LOCATION1=="RIGHT_FOOTDROP"]<-"FEET"
al$LOCATION1[al$LOCATION1=="RIGHT_FOOT"]<-"FEET"
al$LOCATION1[al$LOCATION1=="RIGHT_FOOT__DORSIFLEXORS"]<-"FEET"
al$LOCATION1[al$LOCATION1=="RIGHT_FOOT__ELEVATION"]<-"FEET"
al$LOCATION1[al$LOCATION1=="RIGHT_FOOT__GREATTOE"]<-"FEET"
al$LOCATION1[al$LOCATION1=="ANKLES"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_ANKLE"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_FOOTDROP"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_FOOT__PLANTAR FLEXORS"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_FOOT__DORSIFLEXION"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_FOOT__GREATTOE"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_FOOT"]<-"FEET"
al$LOCATION1[al$LOCATION1=="LEFT_FOOT_ELEVATION"]<-"FEET"

al$LOCATION1[al$LOCATION1=="LEGS__PROXIMAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEGS__DISTAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_CALF"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_THIGH"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_LEG"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_LEG__DISTAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_LEG__PROXIMAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_LEG__UNDER"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_LEG__DORSAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="RIGHT_KNEE"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_KNEE"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_THIGH"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG__DISTAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG__PROXIMAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG__MUSCLES"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG__ANTERIOR TIBIAL"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG__FIBULEOS MUSCLE"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_LEG__PERONEAL MUSCLES"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="THIGHS"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="CALVES"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="KNEES"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="HIPS"]<-"LEGS"
al$LOCATION1[al$LOCATION1=="LEFT_HIP"]<-"LEGS"

al$LOCATION1[al$LOCATION1=="RIGHT_SHOULDER"]<-"SHOULDERS"
al$LOCATION1[al$LOCATION1=="LEFT_SHOULDER"]<-"SHOULDERS"

al$LOCATION1[al$LOCATION1=="MUSCLES"]<-"GENERAL"

al$LOCATION1<- revalue(al$LOCATION1, c("MD"="OTHER"))
al$LOCATION1<- revalue(al$LOCATION1, c("ALTERATION"="OTHER"))
al$LOCATION1<- revalue(al$LOCATION1, c("ANAEPHANYROX"="OTHER"))

al$LOCATION1[al$LOCATION1=="CERVICAL"]<-"NECK"

al$LOCATION1[al$LOCATION1=="DIAPHRAGM"]<-"RESPIRATORY"
al$LOCATION1[al$LOCATION1=="LEFT_INTEROSSEUS"]<-"RESPIRATORY"
al$LOCATION1[al$LOCATION1=="INTEROSSEI"]<-"RESPIRATORY"

al$LOCATION1[al$LOCATION1=="THORACIC"]<-"TRUNK"
al$LOCATION1[al$LOCATION1=="ABDOMEN"]<-"TRUNK"
al$LOCATION1[al$LOCATION1=="BACK__LOW"]<-"TRUNK"
al$LOCATION1[al$LOCATION1=="BACK"]<-"TRUNK"

al$LOCATION1[al$LOCATION1=="DISORDER"]<-"HEAD"

al$LOCATION1[al$LOCATION1=="RIGHT_LOWER LIMB"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="LEFT_LOWER LIMB"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="LEFT_UPPER LIMB"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="LEFT_LIMBS"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="LIMBS__DISTAL"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="RIGHT_LIMBS"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="LOWER LIMBS"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="UPPER LIMBS"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="RIGHT_UPPER LIMB"]<-"LIMBS"
al$LOCATION1[al$LOCATION1=="LEFT_UPPER_LIMB"]<-"LIMBS"

al$LOCATION1[al$LOCATION1=="BULBAR__MUSCLES"]<-"BULBAR"

##### LOCATION 2 ################################################################################

al$LOCATION2[al$LOCATION2=="LEFT_FACE"]<-"FACE"
al$LOCATION2[al$LOCATION2=="TONGUE"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="ORAL__MUSCLES"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="DYSARTHRIA"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="ORAL"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="SLURRING"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="MUMBLING"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="NOSE"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="OROFACIAL"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="DYSATHRIA"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="MOUTH__JAW"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="SLOWING"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="DYSARTHROPHONIA"]<-"MOUTH"
al$LOCATION2[al$LOCATION2=="MOUTH__MASSETER"]<-"MOUTH"

al$LOCATION2[al$LOCATION2=="THROAT"]<-"PHARYNX"
al$LOCATION2[al$LOCATION2=="DYSPHAGIA"]<-"PHARYNX"
al$LOCATION2[al$LOCATION2=="ESOPHAGUS"]<-"PHARYNX"
al$LOCATION2[al$LOCATION2=="NASOPHARYNX"]<-"PHARYNX"


al$LOCATION2<- revalue(al$LOCATION2, c("VOICE"="LARYNX"))
al$LOCATION2<- revalue(al$LOCATION2, c("VOICE__VOLUME"="LARYNX"))
#al$LOCATION2<- revalue(al$LOCATION2, c("DISPHONYA"="LARYNX"))     
#al$LOCATION2<- revalue(al$LOCATION2, c("HOARSENESS"="LARYNX"))    
#al$LOCATION2<- revalue(al$LOCATION2, c("CHOCKING"="LARYNX"))      
al$LOCATION2<- revalue(al$LOCATION2, c("VOCAL CORDS"="LARYNX"))
#al$LOCATION2<- revalue(al$LOCATION2, c("VOICE__MODIFICATION"="LARYNX"))     
#al$LOCATION2<- revalue(al$LOCATION2, c("VARYING PITCH"="LARYNX"))    

al$LOCATION2[al$LOCATION2=="HANDS__FINGERS"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="HANDS__INDEX"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__THUMB"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="LEFT_HAND"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__INTRINSIC MUSCLES"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="LEFT_HAND__FINGERS"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="LEFT_HAND__LITTLE FINGER"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="HANDS__THUMBS"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__LITTLE FINGER"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="LEFT_HAND__INDEX"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__RING"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__INDEX"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="HANDS__MUSCLES"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__FINGERS"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="LEFT_THENAR"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_WRIST"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__MUSCLES"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_HAND__MIDDLE"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="LEFT_HAND__THUMB"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="FINGERS"]<-"HANDS"
al$LOCATION2[al$LOCATION2=="RIGHT_FINGERS"]<-"HANDS"

al$LOCATION2[al$LOCATION2=="FOREARMS"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="RIGHT_ARM"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="RIGHT_ARM__DISTAL"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="RIGHT_ARM__PROXIMAL"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="LEFT_ARM"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="LEFT_FOREARM"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="LEFT_ARM__DISTAL"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="LEFT_ARM__PROXIMAL"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="ARMS__PROXIMAL"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="ARMS__DISTAL"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="ARMS__UPPER"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="RIGHT_FOREARM"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="RIGHT_ELBOW"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="RIGHT_BICEPS"]<-"ARMS"
al$LOCATION2[al$LOCATION2=="LEFT_BICEPS"]<-"ARMS"

al$LOCATION2[al$LOCATION2=="RIGHT_ANKLE"]<-"FEET"
al$LOCATION2[al$LOCATION2=="RIGHT_FOOTDROP"]<-"FEET"
al$LOCATION2[al$LOCATION2=="RIGHT_FOOT"]<-"FEET"
al$LOCATION2[al$LOCATION2=="RIGHT_FOOT__DORSIFLEXORS"]<-"FEET"
al$LOCATION2[al$LOCATION2=="RIGHT_FOOT__ELEVATION"]<-"FEET"
al$LOCATION2[al$LOCATION2=="RIGHT_FOOT__GREATTOE"]<-"FEET"
al$LOCATION2[al$LOCATION2=="ANKLES"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_ANKLE"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_FOOTDROP"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_FOOT__PLANTAR FLEXORS"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_FOOT__DORSIFLEXION"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_FOOT__GREATTOE"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_FOOT"]<-"FEET"
al$LOCATION2[al$LOCATION2=="LEFT_FOOT_ELEVATION"]<-"FEET"
al$LOCATION2[al$LOCATION2=="FEETDROP"]<-"FEET"

al$LOCATION2[al$LOCATION2=="LEGS__PROXIMAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEGS__DISTAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_CALF"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_THIGH"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_THIGH__DISTAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_LEG"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_LEG__DISTAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_LEG__PROXIMAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_LEG__UNDER"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_LEG__DORSAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_KNEE"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_KNEE"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_THIGH"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG__DISTAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG__PROXIMAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG__MUSCLES"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG__ANTERIOR TIBIAL"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG__FIBULEOS MUSCLE"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_LEG__PERONEAL MUSCLES"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="THIGHS"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="CALVES"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="KNEES"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="HIPS"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="LEFT_HIP"]<-"LEGS"
al$LOCATION2[al$LOCATION2=="RIGHT_HIP"]<-"LEGS"

al$LOCATION2<- revalue(al$LOCATION2, c("RIGHT_SHOULDER"="SHOULDERS"))
#al$LOCATION2<- revalue(al$LOCATION2, c("LEFT_SHOULDER"="SHOULDERS"))           

#al$LOCATION2<- revalue(al$LOCATION2, c("MUSCLES"="GENERAL"))                   

#al$LOCATION2<- revalue(al$LOCATION2, c("MD"="OTHER"))                         
#al$LOCATION2<- revalue(al$LOCATION2, c("ALTERATION"="OTHER"))                 
#al$LOCATION2<- revalue(al$LOCATION2, c("ANAEPHANYROX"="OTHER"))               

al$LOCATION2[al$LOCATION2=="CERVICAL"]<-"NECK"

#al$LOCATION2<- revalue(al$LOCATION2, c("DIAPHRAGM"="RESPIRATORY"))             
al$LOCATION2<- revalue(al$LOCATION2, c("LEFT_INTEROSSEUS"="RESPIRATORY"))     
#al$LOCATION2<- revalue(al$LOCATION2, c("INTEROSSEI"="RESPIRATORY"))            

#al$LOCATION2<- revalue(al$LOCATION2, c("THORACIC"="TRUNK"))                   
al$LOCATION2<- revalue(al$LOCATION2, c("ABDOMEN"="TRUNK"))
al$LOCATION2<- revalue(al$LOCATION2, c("BACK__LOW"="TRUNK"))
al$LOCATION2<- revalue(al$LOCATION2, c("BACK"="TRUNK"))

#al$LOCATION2<- revalue(al$LOCATION2, c("DISORDER"="HEAD"))                    

al$LOCATION2[al$LOCATION2=="RIGHT_LOWER LIMB"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LEFT_LOWER LIMB"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LEFT_UPPER LIMB"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LEFT_LIMBS"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LIMBS__DISTAL"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="RIGHT_LIMBS"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LOWER LIMBS"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="UPPER LIMBS"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="RIGHT_UPPER LIMB"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LEFT_UPPER_LIMB"]<-"LIMBS"
al$LOCATION2[al$LOCATION2=="LEFT_UPPER LIMBS"]<-"LIMBS"

al$LOCATION2[al$LOCATION2=="BULBAR__MUSCLES"]<-"BULBAR"


##### LOCATION 3 ################################################################################
al$LOCATION3[al$LOCATION3=="LEFT_FACE"]<-"FACE"

al$LOCATION3<- revalue(al$LOCATION3, c("TONGUE"="MOUTH"))
al$LOCATION3[al$LOCATION3=="ORAL__MUSCLES"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="DYSARTHRIA"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="ORAL"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="SLURRING"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="MUMBLING"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="NOSE"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="OROFACIAL"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="DYSATHRIA"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="MOUTH__JAW"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="SLOWING"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="DYSARTHROPHONIA"]<-"MOUTH"
al$LOCATION3[al$LOCATION3=="MOUTH__MASSETER"]<-"MOUTH"

#al$LOCATION3<- revalue(al$LOCATION3, c("THROAT"="PHARYNX"))
#al$LOCATION3<- revalue(al$LOCATION3, c("DYSPHAGIA"="PHARYNX"))
#al$LOCATION3<- revalue(al$LOCATION3, c("ESOPHAGUS"="PHARYNX"))
#al$LOCATION3<- revalue(al$LOCATION3, c("NASOPHARYNX"="PHARYNX"))

#al$LOCATION3<- revalue(al$LOCATION3, c("VOICE"="LARYNX"))
#al$LOCATION3<- revalue(al$LOCATION3, c("VOICE__VOLUME"="LARYNX"))
#al$LOCATION3<- revalue(al$LOCATION3, c("DISPHONYA"="LARYNX"))     
#al$LOCATION3<- revalue(al$LOCATION3, c("HOARSENESS"="LARYNX"))    
#al$LOCATION3<- revalue(al$LOCATION3, c("CHOCKING"="LARYNX"))      
#al$LOCATION3<- revalue(al$LOCATION3, c("VOCAL CORDS"="LARYNX"))
#al$LOCATION3<- revalue(al$LOCATION3, c("VOICE__MODIFICATION"="LARYNX"))     
#al$LOCATION3<- revalue(al$LOCATION3, c("VARYING PITCH"="LARYNX"))     

al$LOCATION3[al$LOCATION3=="HANDS__FINGERS"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="HANDS__INDEX"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__THUMB"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="LEFT_HAND"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__INTRINSIC MUSCLES"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="LEFT_HAND__FINGERS"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="LEFT_HAND__LITTLE FINGER"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="HANDS__THUMBS"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__LITTLE FINGER"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="LEFT_HAND__INDEX"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__RING"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__INDEX"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="HANDS__MUSCLES"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__FINGERS"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="LEFT_THENAR"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_WRIST"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__MUSCLES"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_HAND__MIDDLE"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="LEFT_HAND__THUMB"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="FINGERS"]<-"HANDS"
al$LOCATION3[al$LOCATION3=="RIGHT_FINGERS"]<-"HANDS"

#al$LOCATION3<- revalue(al$LOCATION3, c("FOREARMS"="ARMS"))  
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_ARM"="ARMS"))  
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_ARM__DISTAL"="ARMS"))  
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_ARM__PROXIMAL"="ARMS"))  
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_ARM"="ARMS"))  
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOREARM"="ARMS"))  
al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_ARM__DISTAL"="ARMS"))  
al$LOCATION3[al$LOCATION3=="LEFT_ARM__PROXIMAL"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="ARMS__PROXIMAL"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="ARMS__DISTAL"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="ARMS__UPPER"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="RIGHT_FOREARM"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="RIGHT_ELBOW"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="RIGHT_BICEPS"]<-"ARMS"
al$LOCATION3[al$LOCATION3=="LEFT_BICEPS"]<-"ARMS"

#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_ANKLE"="FEET"))  
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_FOOTDROP"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_FOOT"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_FOOT__DORSIFLEXORS"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_FOOT__ELEVATION"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_FOOT__GREATTOE"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("ANKLES"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_ANKLE"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOOTDROP"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOOT__PLANTAR FLEXORS"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOOT__DORSIFLEXION"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOOT__GREATTOE"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOOT"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_FOOT_ELEVATION"="FEET")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("FEETDROP"="FEET")) 

al$LOCATION3[al$LOCATION3=="LEGS__PROXIMAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEGS__DISTAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_CALF"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_THIGH"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_THIGH__DISTAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_LEG"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_LEG__DISTAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_LEG__PROXIMAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_LEG__UNDER"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_LEG__DORSAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_KNEE"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_KNEE"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_THIGH"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG__DISTAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG__PROXIMAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG__MUSCLES"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG__ANTERIOR TIBIAL"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG__FIBULEOS MUSCLE"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_LEG__PERONEAL MUSCLES"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="THIGHS"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="CALVES"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="KNEES"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="HIPS"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="LEFT_HIP"]<-"LEGS"
al$LOCATION3[al$LOCATION3=="RIGHT_HIP"]<-"LEGS"

#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_SHOULDER"="SHOULDERS"))
al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_SHOULDER"="SHOULDERS"))           

#al$LOCATION3<- revalue(al$LOCATION3, c("MUSCLES"="GENERAL"))                   

#al$LOCATION3<- revalue(al$LOCATION3, c("MD"="OTHER"))                         
#al$LOCATION3<- revalue(al$LOCATION3, c("ALTERATION"="OTHER"))                 
#al$LOCATION3<- revalue(al$LOCATION3, c("ANAEPHANYROX"="OTHER"))               

#al$LOCATION3<- revalue(al$LOCATION3, c("CERVICAL"="NECK"))           

#al$LOCATION3<- revalue(al$LOCATION3, c("DIAPHRAGM"="RESPIRATORY"))             
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_INTEROSSEUS"="RESPIRATORY"))     
#al$LOCATION3<- revalue(al$LOCATION3, c("INTEROSSEI"="RESPIRATORY"))            

#al$LOCATION3<- revalue(al$LOCATION3, c("THORACIC"="TRUNK"))                   
#al$LOCATION3<- revalue(al$LOCATION3, c("ABDOMEN"="TRUNK"))
#al$LOCATION3<- revalue(al$LOCATION3, c("BACK__LOW"="TRUNK"))
#al$LOCATION3<- revalue(al$LOCATION3, c("BACK"="TRUNK"))
al$LOCATION3<- revalue(al$LOCATION3, c("CHEST"="TRUNK"))


#al$LOCATION3<- revalue(al$LOCATION3, c("DISORDER"="HEAD"))                    

#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_LOWER LIMB"="LIMBS")) 
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_LOWER LIMB"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_UPPER LIMB"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_LIMBS"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("LIMBS__DISTAL"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_LIMBS"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("LOWER LIMBS"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("UPPER LIMBS"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_UPPER LIMB"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_UPPER_LIMB"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("RIGHT_LIMBS"="LIMBS"))           
#al$LOCATION3<- revalue(al$LOCATION3, c("LEFT_UPPER LIMBS"="LIMBS"))           

#al$LOCATION3<- revalue(al$LOCATION3, c("BULBAR__MUSCLES"="BULBAR"))           

##### LOCATION 4 ################################################################################

# al$LOCATION4[al$LOCATION4=="LEFT_FACE"]<-"FACE"
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("TONGUE"="MOUTH"))
# al$LOCATION4[al$LOCATION4=="ORAL__MUSCLES"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="DYSARTHRIA"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="ORAL"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="SLURRING"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="MUMBLING"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="NOSE"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="OROFACIAL"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="DYSATHRIA"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="MOUTH__JAW"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="SLOWING"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="DYSARTHROPHONIA"]<-"MOUTH"
# al$LOCATION4[al$LOCATION4=="MOUTH__MASSETER"]<-"MOUTH"
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("THROAT"="PHARYNX"))
# al$LOCATION4<- revalue(al$LOCATION4, c("DYSPHAGIA"="PHARYNX"))
# al$LOCATION4<- revalue(al$LOCATION4, c("ESOPHAGUS"="PHARYNX"))
# al$LOCATION4<- revalue(al$LOCATION4, c("NASOPHARYNX"="PHARYNX"))
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("VOICE"="LARYNX"))
# al$LOCATION4<- revalue(al$LOCATION4, c("VOICE__VOLUME"="LARYNX"))
# al$LOCATION4<- revalue(al$LOCATION4, c("DISPHONYA"="LARYNX"))     
# al$LOCATION4<- revalue(al$LOCATION4, c("HOARSENESS"="LARYNX"))    
# al$LOCATION4<- revalue(al$LOCATION4, c("CHOCKING"="LARYNX"))      
# al$LOCATION4<- revalue(al$LOCATION4, c("VOCAL CORDS"="LARYNX"))
# al$LOCATION4<- revalue(al$LOCATION4, c("VOICE__MODIFICATION"="LARYNX"))     
# al$LOCATION4<- revalue(al$LOCATION4, c("VARYING PITCH"="LARYNX"))     
# 
# al$LOCATION4[al$LOCATION4=="HANDS__FINGERS"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="HANDS__INDEX"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__THUMB"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="LEFT_HAND"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__INTRINSIC MUSCLES"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="LEFT_HAND__FINGERS"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="LEFT_HAND__LITTLE FINGER"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="HANDS__THUMBS"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__LITTLE FINGER"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="LEFT_HAND__INDEX"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__RING"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__INDEX"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="HANDS__MUSCLES"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__FINGERS"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="LEFT_THENAR"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_WRIST"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__MUSCLES"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HAND__MIDDLE"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="LEFT_HAND__THUMB"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="FINGERS"]<-"HANDS"
# al$LOCATION4[al$LOCATION4=="RIGHT_FINGERS"]<-"HANDS"
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("FOREARMS"="ARMS"))  
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_ARM"="ARMS"))  
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_ARM__DISTAL"="ARMS"))  
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_ARM__PROXIMAL"="ARMS"))  
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_ARM"="ARMS"))  
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOREARM"="ARMS"))  
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_ARM__DISTAL"="ARMS"))  
# al$LOCATION4[al$LOCATION4=="LEFT_ARM__PROXIMAL"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="ARMS__PROXIMAL"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="ARMS__DISTAL"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="ARMS__UPPER"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="RIGHT_FOREARM"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="RIGHT_ELBOW"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="RIGHT_BICEPS"]<-"ARMS"
# al$LOCATION4[al$LOCATION4=="LEFT_BICEPS"]<-"ARMS"
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_ANKLE"="FEET"))  
al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_FOOTDROP"="FEET")) 
#al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_FOOT"="FEET"))
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_FOOT__DORSIFLEXORS"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_FOOT__ELEVATION"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_FOOT__GREATTOE"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("ANKLES"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_ANKLE"="FEET")) 
al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOOTDROP"="FEET"))
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOOT__PLANTAR FLEXORS"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOOT__DORSIFLEXION"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOOT__GREATTOE"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOOT"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_FOOT_ELEVATION"="FEET")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("FEETDROP"="FEET")) 
# 
# al$LOCATION4[al$LOCATION4=="LEGS__PROXIMAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEGS__DISTAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_CALF"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_THIGH"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_THIGH__DISTAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_LEG"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_LEG__DISTAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_LEG__PROXIMAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_LEG__UNDER"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_LEG__DORSAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_KNEE"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_KNEE"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_THIGH"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG__DISTAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG__PROXIMAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG__MUSCLES"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG__ANTERIOR TIBIAL"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG__FIBULEOS MUSCLE"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_LEG__PERONEAL MUSCLES"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="THIGHS"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="CALVES"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="KNEES"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="HIPS"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="LEFT_HIP"]<-"LEGS"
# al$LOCATION4[al$LOCATION4=="RIGHT_HIP"]<-"LEGS"
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_SHOULDER"="SHOULDERS"))
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_SHOULDER"="SHOULDERS"))           
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("MUSCLES"="GENERAL"))                   
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("MD"="OTHER"))                         
# al$LOCATION4<- revalue(al$LOCATION4, c("ALTERATION"="OTHER"))                 
# al$LOCATION4<- revalue(al$LOCATION4, c("ANAEPHANYROX"="OTHER"))               
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("CERVICAL"="NECK"))           
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("DIAPHRAGM"="RESPIRATORY"))             
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_INTEROSSEUS"="RESPIRATORY"))     
# al$LOCATION4<- revalue(al$LOCATION4, c("INTEROSSEI"="RESPIRATORY"))            
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("THORACIC"="TRUNK"))                   
# al$LOCATION4<- revalue(al$LOCATION4, c("ABDOMEN"="TRUNK"))
# al$LOCATION4<- revalue(al$LOCATION4, c("BACK__LOW"="TRUNK"))
# al$LOCATION4<- revalue(al$LOCATION4, c("BACK"="TRUNK"))
# al$LOCATION4<- revalue(al$LOCATION4, c("CHEST"="TRUNK"))
# 
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("DISORDER"="HEAD"))                    
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_LOWER LIMB"="LIMBS")) 
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_LOWER LIMB"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_UPPER LIMB"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_LIMBS"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("LIMBS__DISTAL"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_LIMBS"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("LOWER LIMBS"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("UPPER LIMBS"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_UPPER LIMB"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_UPPER_LIMB"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("RIGHT_LIMBS"="LIMBS"))           
# al$LOCATION4<- revalue(al$LOCATION4, c("LEFT_UPPER LIMBS"="LIMBS"))           
# 
# al$LOCATION4<- revalue(al$LOCATION4, c("BULBAR__MUSCLES"="BULBAR"))

##### LOCATION 5 ################################################################################

# al$LOCATION5[al$LOCATION5=="LEFT_FACE"]<-"FACE"
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("TONGUE"="MOUTH"))
# al$LOCATION5[al$LOCATION5=="ORAL__MUSCLES"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="DYSARTHRIA"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="ORAL"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="SLURRING"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="MUMBLING"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="NOSE"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="OROFACIAL"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="DYSATHRIA"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="MOUTH__JAW"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="SLOWING"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="DYSARTHROPHONIA"]<-"MOUTH"
# al$LOCATION5[al$LOCATION5=="MOUTH__MASSETER"]<-"MOUTH"
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("THROAT"="PHARYNX"))
# al$LOCATION5<- revalue(al$LOCATION5, c("DYSPHAGIA"="PHARYNX"))
# al$LOCATION5<- revalue(al$LOCATION5, c("ESOPHAGUS"="PHARYNX"))
# al$LOCATION5<- revalue(al$LOCATION5, c("NASOPHARYNX"="PHARYNX"))
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("VOICE"="LARYNX"))
# al$LOCATION5<- revalue(al$LOCATION5, c("VOICE__VOLUME"="LARYNX"))
# al$LOCATION5<- revalue(al$LOCATION5, c("DISPHONYA"="LARYNX"))     
# al$LOCATION5<- revalue(al$LOCATION5, c("HOARSENESS"="LARYNX"))    
# al$LOCATION5<- revalue(al$LOCATION5, c("CHOCKING"="LARYNX"))      
# al$LOCATION5<- revalue(al$LOCATION5, c("VOCAL CORDS"="LARYNX"))
# al$LOCATION5<- revalue(al$LOCATION5, c("VOICE__MODIFICATION"="LARYNX"))     
# al$LOCATION5<- revalue(al$LOCATION5, c("VARYING PITCH"="LARYNX"))     
# 
# al$LOCATION5[al$LOCATION5=="HANDS__FINGERS"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="HANDS__INDEX"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__THUMB"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="LEFT_HAND"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__INTRINSIC MUSCLES"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="LEFT_HAND__FINGERS"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="LEFT_HAND__LITTLE FINGER"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="HANDS__THUMBS"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__LITTLE FINGER"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="LEFT_HAND__INDEX"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__RING"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__INDEX"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="HANDS__MUSCLES"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__FINGERS"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="LEFT_THENAR"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_WRIST"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__MUSCLES"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HAND__MIDDLE"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="LEFT_HAND__THUMB"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="FINGERS"]<-"HANDS"
# al$LOCATION5[al$LOCATION5=="RIGHT_FINGERS"]<-"HANDS"
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("FOREARMS"="ARMS"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_ARM"="ARMS"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_ARM__DISTAL"="ARMS"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_ARM__PROXIMAL"="ARMS"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_ARM"="ARMS"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOREARM"="ARMS"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_ARM__DISTAL"="ARMS"))  
# al$LOCATION5[al$LOCATION5=="LEFT_ARM__PROXIMAL"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="ARMS__PROXIMAL"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="ARMS__DISTAL"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="ARMS__UPPER"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="RIGHT_FOREARM"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="RIGHT_ELBOW"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="RIGHT_BICEPS"]<-"ARMS"
# al$LOCATION5[al$LOCATION5=="LEFT_BICEPS"]<-"ARMS"
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_ANKLE"="FEET"))  
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_FOOTDROP"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_FOOT"="FEET"))
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_FOOT__DORSIFLEXORS"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_FOOT__ELEVATION"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_FOOT__GREATTOE"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("ANKLES"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_ANKLE"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOOTDROP"="FEET"))
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOOT__PLANTAR FLEXORS"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOOT__DORSIFLEXION"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOOT__GREATTOE"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOOT"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_FOOT_ELEVATION"="FEET")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("FEETDROP"="FEET")) 
# 
# al$LOCATION5[al$LOCATION5=="LEGS__PROXIMAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEGS__DISTAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_CALF"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_THIGH"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_THIGH__DISTAL"]<-"LEGS"
al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_LEG"="LEGS"))
# al$LOCATION5[al$LOCATION5=="RIGHT_LEG__DISTAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_LEG__PROXIMAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_LEG__UNDER"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_LEG__DORSAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_KNEE"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_KNEE"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_THIGH"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG__DISTAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG__PROXIMAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG__MUSCLES"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG__ANTERIOR TIBIAL"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG__FIBULEOS MUSCLE"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_LEG__PERONEAL MUSCLES"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="THIGHS"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="CALVES"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="KNEES"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="HIPS"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="LEFT_HIP"]<-"LEGS"
# al$LOCATION5[al$LOCATION5=="RIGHT_HIP"]<-"LEGS"
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_SHOULDER"="SHOULDERS"))
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_SHOULDER"="SHOULDERS"))           
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("MUSCLES"="GENERAL"))                   
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("MD"="OTHER"))                         
# al$LOCATION5<- revalue(al$LOCATION5, c("ALTERATION"="OTHER"))                 
# al$LOCATION5<- revalue(al$LOCATION5, c("ANAEPHANYROX"="OTHER"))               
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("CERVICAL"="NECK"))           
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("DIAPHRAGM"="RESPIRATORY"))             
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_INTEROSSEUS"="RESPIRATORY"))     
# al$LOCATION5<- revalue(al$LOCATION5, c("INTEROSSEI"="RESPIRATORY"))            
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("THORACIC"="TRUNK"))                   
# al$LOCATION5<- revalue(al$LOCATION5, c("ABDOMEN"="TRUNK"))
# al$LOCATION5<- revalue(al$LOCATION5, c("BACK__LOW"="TRUNK"))
# al$LOCATION5<- revalue(al$LOCATION5, c("BACK"="TRUNK"))
# al$LOCATION5<- revalue(al$LOCATION5, c("CHEST"="TRUNK"))
# 
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("DISORDER"="HEAD"))                    
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_LOWER LIMB"="LIMBS")) 
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_LOWER LIMB"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_UPPER LIMB"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_LIMBS"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("LIMBS__DISTAL"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_LIMBS"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("LOWER LIMBS"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("UPPER LIMBS"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_UPPER LIMB"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_UPPER_LIMB"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("RIGHT_LIMBS"="LIMBS"))           
# al$LOCATION5<- revalue(al$LOCATION5, c("LEFT_UPPER LIMBS"="LIMBS"))           
# 
# al$LOCATION5<- revalue(al$LOCATION5, c("BULBAR__MUSCLES"="BULBAR"))


##### UNIONE LOCATION ################################################################################
# levels(al$LOCATION1)<-factor(al$LOCATION1)
# levels(al$LOCATION2)<-factor(al$LOCATION2)
# levels(al$LOCATION3)<-factor(al$LOCATION3)
# levels(al$LOCATION4)<-factor(al$LOCATION4)
# levels(al$LOCATION5)<-factor(al$LOCATION5)

N = dim.data.frame(al)[1]
library(pracma)
for (i in 1:N) {
  if ((as.character(al$LOCATION1[i])==as.character(al$LOCATION2[i]))&(!is.na(al$LOCATION1[i]))){   #1vs2
    al$LOCATION2[i] <- ""
 }
  if ((as.character(al$LOCATION1[i])==as.character(al$LOCATION3[i]))&(!is.na(al$LOCATION1[i]))){   #1vs3
    al$LOCATION3[i] <- ""
  }
  if ((as.character(al$LOCATION1[i])==as.character(al$LOCATION4[i]))&(!is.na(al$LOCATION1[i]))){   #1vs4
    al$LOCATION4[i] <- ""
  }
  if ((as.character(al$LOCATION1[i])==as.character(al$LOCATION5[i]))&(!is.na(al$LOCATION1[i]))){   #1vs5
    al$LOCATION5[i] <- ""
  }
  if (as.character(al$LOCATION2[i])==as.character(al$LOCATION3[i])){   #2vs3
    al$LOCATION3[i] <- ""
  }
  if (as.character(al$LOCATION2[i])==as.character(al$LOCATION4[i])){   #2vs4
    al$LOCATION4[i] <- ""
  }
  if (as.character(al$LOCATION2[i])==as.character(al$LOCATION5[i])){   #2vs5
    al$LOCATION5[i] <- ""
  }
  if (as.character(al$LOCATION3[i])==as.character(al$LOCATION4[i])){   #3vs4
    al$LOCATION4[i] <- ""
  }
  if (as.character(al$LOCATION3[i])==as.character(al$LOCATION5[i])){   #3vs5
    al$LOCATION5[i] <- ""
  }
  if (as.character(al$LOCATION4[i])==as.character(al$LOCATION5[i])){   #4vs5
    al$LOCATION5[i] <- ""
  }
}
# ora posso cancellare LOCATION5, è colonna nulla
al[,"LOCATION5"] <- NULL
  
rm(als)
rm(i)
rm(N)

## Scrivo il dataset
write.csv(al, "Filtered_NEW/Filtered_ALSHistory_Subject_symptoms.csv", row.names = FALSE)

